---
version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      sorbet:
        patterns:
          - "*-sorbet"
          - "sorbet-*"
          - "*sorbet*"
          - "tapioca"
    labels:
      - "automerge"
      - "dependencies"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "automerge"
      - "dependencies"
