---
inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-sorbet

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - 'sorbet/**/*'  # VSCode plugin workaround
    - 'spec/data/**/*'
  NewCops: enable
  TargetRubyVersion: 2.5

Layout/ClassStructure:
  Enabled: true
# doesn't recognize sorbet magic comments
Layout/EmptyLineAfterMagicComment:
  Enabled: false
Metrics:
  Severity: info
Metrics/BlockLength:
  Exclude:
    - spec/yard_sorbet/**/*
Naming/FileName:
  Exclude:
    - lib/yard-sorbet.rb
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
Sorbet/StrictSigil:
  Enabled: true
  Exclude:
    - Gemfile
    - Rakefile
    - spec/yard_sorbet/**/*
Style/AccessModifierDeclarations:
  EnforcedStyle: inline
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/NegatedIf:
  Enabled: false
Style/NegatedWhile:
  Enabled: false
Style/Next:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
