---
require:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-sorbet

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

Layout/ClassStructure:
  Enabled: true
Naming/FileName:
  Exclude:
    - lib/yard-sorbet.rb
Sorbet/ForbidTUntyped:
  Enabled: true
Sorbet/StrictSigil:
  Enabled: true
