---
require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-sorbet

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - spec/data/**/*
  NewCops: enable
  TargetRubyVersion: 2.6

Layout/ClassStructure:
  Enabled: true
Naming/FileName:
  Exclude:
    - lib/yard-sorbet.rb
Sorbet/StrictSigil:
  Enabled: true
