---
require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-sorbet

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - 'spec/data/**/*'
  NewCops: enable
  TargetRubyVersion: 2.5

Layout/ClassStructure:
  Enabled: true
Metrics/BlockLength:
  Exclude:
    - spec/yard_sorbet/**/*
Naming/FileName:
  Exclude:
    - lib/yard-sorbet.rb
Sorbet/StrictSigil:
  Enabled: true
