---
require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-sorbet

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - '**/*.rbi'  # VSCode plugin workaround
    - 'spec/data/**/*'
  NewCops: enable
  TargetRubyVersion: 2.6

Layout/ClassStructure:
  Enabled: true
# doesn't recognize sorbet magic comments
Layout/EmptyLineAfterMagicComment:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - spec/yard_sorbet/**/*
Naming/FileName:
  Exclude:
    - lib/yard-sorbet.rb
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
Sorbet/StrictSigil:
  Enabled: true
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/IfUnlessModifier:
  Enabled: false
