---
gem:
  exclude:
    - ast
    - byebug
    - coderay
    - diff-lcs
    - docile
    - erubi
    - json
    - language_server-protocol
    - netrc
    - parallel
    - parser
    - prettier_print
    - prism
    - pry-byebug
    - racc
    - rainbow
    - rbi
    - redcarpet
    - regexp_parser
    - rexml
    - rubocop-ast
    - rubocop-capybara
    - rubocop-factory_bot
    - rubocop-packaging
    - rubocop-performance
    - rubocop-rake
    - rubocop-rspec
    - rubocop-sorbet
    - rubocop
    - ruby-progressbar
    - simplecov-html
    - simplecov_json_formatter
    - spoom
    - syntax_tree
    - tapioca
    - thor
    - unicode-display_width
